name: Haskell CI

on:
    push:
        branches: [ "master" ]
    pull_request:
        branches: [ "master" ]
    workflow_dispatch: {}

permissions:
    contents: read

jobs:
    build:
        strategy:
            fail-fast: false
            matrix:
                os:
                - ubuntu-latest
                - macOS-latest
                ghc:
                - "9.6.6"
                - "9.8.4"
                - "9.10.1"

        runs-on: ${{matrix.os}}

        steps:
        -
            uses: actions/checkout@v4
        -
            uses: haskell-actions/setup@v2
            id: setup-haskell-cabal
            with:
                ghc-version: ${{matrix.ghc}}
        -
            name: Cache
            uses: actions/cache@v4
            env:
                cache-name: cache-cabal
            with:
                path: |
                    ${{steps.setup-haskell-cabal.outputs.cabal-store}}
                    dist-newstyle
                key: ${{runner.os}}-${{matrix.ghc}}
        -
            name: Install dependencies
            run: |
                cabal update
                cabal build --only-dependencies --enable-tests --enable-benchmarks
        -
            name: Build & Test
            run: |
                cabal v1-install --only-dependencies --enable-tests
                cabal v1-configure --enable-tests
                cabal v1-test
        -
            name: Haddock
            run: cabal v1-haddock
